name: "Main"

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  TERM: dumb

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: test
        run: |
          ./gradlew test
